services:
  redis:
    image: redis:7-alpine
    container_name: redis_lab
    restart: always
    ports:
      - "6379:6379"
    networks:
      - lab_net

  lab_secure:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: insecure_design_lab
    volumes:
      - ../code:/app/code
      - ../tests:/app/tests
      - ../logs:/app/logs
      - ../requirements.txt:/app/requirements.txt
    depends_on:
      - redis
    networks:
      - lab_net
    command: ["tail", "-f", "/dev/null"]

  lab_api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: secure_api_lab
    volumes:
      - ../code:/app/code
      - ../logs:/app/logs
      - ../requirements.txt:/app/requirements.txt
    depends_on:
      - redis
    ports:
      - "8000:8000"
    networks:
      - lab_net
    command: ["uvicorn", "code.secure.api:app", "--host", "0.0.0.0", "--port", "8000"]

networks:
  lab_net:
    driver: bridge

